
base:
  url: /

db:
  host: localhost
  user: dbuser
  password: dbpass
  name: qsnet

arp:
  - host: first-routeros-IP-here
    community: public
    oid: 1.3.6.1.2.1.4.22
  - host: second-routeros-IP-here
    community: public
    oid: 1.3.6.1.2.1.4.22
  - host: other-routeros-IP-here
    community: public
    oid: 1.3.6.1.2.1.4.22

accountig:
  host: 
  url: 

auth:
  login: test
  pass: testPwd
  
