
base:
  url: /

db:
  host: localhost
  user: dbuser
  password: dbpass
  name: qsnet

arp:
  - host: first-routeros-IP-here
    community: public
    oid: 1.3.6.1.2.1.4.22
  - host: second-routeros-IP-here
    community: public
    oid: 1.3.6.1.2.1.4.22
  - host: other-routeros-IP-here
    community: public
    oid: 1.3.6.1.2.1.4.22

accounting:
  local: 192\.168\.[0-9]{1,3}\.[0-9]{1,3}
  sources:
    - http://{firts_ros_ip}/accounting/ip.cgi
    - http://another/accounting/url
    - /or/local/path/to/source/file

auth:
  login: test
  pass: testPwd
  
